//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood
{
    public partial class NotificationsPage
    {
        /// <summary>
        /// roleSidebar control.
        /// </summary>
        protected global::LeftoverFood.Controls.RoleSidebar roleSidebar;

        /// <summary>
        /// litSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSummary;

        /// <summary>
        /// btnMarkAll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnMarkAll;

        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// litMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMessage;

        /// <summary>
        /// btnFilterAll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnFilterAll;

        /// <summary>
        /// btnFilterUnread control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnFilterUnread;

        /// <summary>
        /// rptNotifications control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptNotifications;

        /// <summary>
        /// pnlEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        /// <summary>
        /// litEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmpty;
    }
}
