//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood
{
    public partial class ProfilePage
    {
        /// <summary>
        /// roleSidebar control.
        /// </summary>
        protected global::LeftoverFood.Controls.RoleSidebar roleSidebar;

        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// litMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMessage;

        /// <summary>
        /// litHeroStats control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeroStats;

        /// <summary>
        /// litVerifiedChip control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litVerifiedChip;

        /// <summary>
        /// txtFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>
        /// txtRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRole;

        /// <summary>
        /// ddlCity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCity;

        /// <summary>
        /// txtStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStatus;

        /// <summary>
        /// litAddressLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAddressLabel;

        /// <summary>
        /// txtAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress;

        /// <summary>
        /// txtBio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBio;

        /// <summary>
        /// btnSavePersonal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSavePersonal;

        /// <summary>
        /// pnlOrg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlOrg;

        /// <summary>
        /// litOrgHeading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litOrgHeading;

        /// <summary>
        /// txtOrgName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtOrgName;

        /// <summary>
        /// pnlBusinessType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlBusinessType;

        /// <summary>
        /// ddlBusinessType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlBusinessType;

        /// <summary>
        /// litRegLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRegLabel;

        /// <summary>
        /// txtRegNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRegNumber;

        /// <summary>
        /// pnlPreferredNgo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPreferredNgo;

        /// <summary>
        /// ddlPreferredNGO control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlPreferredNGO;

        /// <summary>
        /// btnSaveOrg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveOrg;

        /// <summary>
        /// pnlVolunteerLocation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlVolunteerLocation;

        /// <summary>
        /// litShareLocation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litShareLocation;

        /// <summary>
        /// pnlPwMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPwMessage;

        /// <summary>
        /// litPwMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPwMessage;

        /// <summary>
        /// txtCurrentPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;

        /// <summary>
        /// txtNewPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;

        /// <summary>
        /// txtConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        /// <summary>
        /// btnChangePassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnChangePassword;

        /// <summary>
        /// pnlTrust control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTrust;

        /// <summary>
        /// litTrustScore control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTrustScore;

        /// <summary>
        /// litTrustDetail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTrustDetail;

        /// <summary>
        /// litAccountId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAccountId;

        /// <summary>
        /// litJoined control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litJoined;

        /// <summary>
        /// litLastLogin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLastLogin;

        /// <summary>
        /// litApproval control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litApproval;

        /// <summary>
        /// litAccountStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAccountStatus;

        /// <summary>
        /// rptActivity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptActivity;

        /// <summary>
        /// pnlNoActivity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoActivity;
    }
}
