//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood
{
    public partial class RatingsPage
    {
        /// <summary>
        /// roleSidebar control.
        /// </summary>
        protected global::LeftoverFood.Controls.RoleSidebar roleSidebar;

        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// litMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMessage;

        /// <summary>
        /// pnlNoReceived control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoReceived;

        /// <summary>
        /// pnlBreakdown control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlBreakdown;

        /// <summary>
        /// rptHistogram control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptHistogram;

        /// <summary>
        /// pnlNothingToRate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNothingToRate;

        /// <summary>
        /// litNothingToRate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNothingToRate;

        /// <summary>
        /// pnlRateForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlRateForm;

        /// <summary>
        /// ddlRateable control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRateable;

        /// <summary>
        /// txtComments control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtComments;

        /// <summary>
        /// btnSubmitRating control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSubmitRating;

        /// <summary>
        /// ddlReviewFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlReviewFilter;

        /// <summary>
        /// rptReceived control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptReceived;

        /// <summary>
        /// pnlNoReviews control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoReviews;

        /// <summary>
        /// litNoReviews control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNoReviews;

        /// <summary>
        /// pnlGiven control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlGiven;

        /// <summary>
        /// rptGiven control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptGiven;
    }
}
