//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood
{
    public partial class SearchPage
    {
        /// <summary>
        /// roleSidebar control.
        /// </summary>
        protected global::LeftoverFood.Controls.RoleSidebar roleSidebar;

        /// <summary>
        /// litScopeNote control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litScopeNote;

        /// <summary>
        /// litSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSummary;

        /// <summary>
        /// pnlPrompt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPrompt;

        /// <summary>
        /// pnlDonations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlDonations;

        /// <summary>
        /// litDonationCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDonationCount;

        /// <summary>
        /// rptDonations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptDonations;

        /// <summary>
        /// pnlNoDonations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoDonations;

        /// <summary>
        /// pnlUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlUsers;

        /// <summary>
        /// litUserCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUserCount;

        /// <summary>
        /// rptUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptUsers;

        /// <summary>
        /// pnlNoUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoUsers;

        /// <summary>
        /// pnlNothing control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNothing;

        /// <summary>
        /// litNothingTerm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNothingTerm;

        /// <summary>
        /// litNothingHint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNothingHint;
    }
}
