//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood
{


    public partial class SiteMaster
    {

        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder SidebarContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder PageHeading;

        protected global::System.Web.UI.HtmlControls.HtmlAnchor notifBell;

        protected global::System.Web.UI.WebControls.Literal litBellBadge;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl topbarAvatar;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder FooterScripts;
    }
}
