//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.NGO
{


    public partial class ngo_dashboard
    {

        protected global::System.Web.UI.WebControls.Label lblActionMessage;

        protected global::System.Web.UI.WebControls.Literal litNewRequests;

        protected global::System.Web.UI.WebControls.Literal litAcceptedToday;

        protected global::System.Web.UI.WebControls.Literal litAvailableBadge;

        protected global::System.Web.UI.WebControls.Repeater rptAvailable;

        protected global::System.Web.UI.WebControls.Panel pnlNoAvailable;

        protected global::System.Web.UI.WebControls.Literal litVerifiedBadge;

        protected global::System.Web.UI.WebControls.Literal litInTransit;

        protected global::System.Web.UI.WebControls.Literal litMealsServed;

        protected global::System.Web.UI.WebControls.Repeater rptActiveDeliveries;

        protected global::System.Web.UI.WebControls.Panel pnlNoActive;

        protected global::System.Web.UI.WebControls.Repeater rptVolunteers;

        protected global::System.Web.UI.WebControls.Panel pnlNoVolunteers;

        protected global::System.Web.UI.WebControls.Literal litMonthLabel;

        protected global::System.Web.UI.WebControls.Literal litMonthAccepted;

        protected global::System.Web.UI.WebControls.Literal litMonthMeals;

        protected global::System.Web.UI.WebControls.Literal litMonthFulfilment;
    }
}
