//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.NGO
{


    public partial class ngo_dashboard
    {

        protected global::System.Web.UI.WebControls.Label lblActionMessage;

        protected global::System.Web.UI.WebControls.Literal litNewRequests;

        protected global::System.Web.UI.WebControls.Literal litAcceptedToday;

        protected global::System.Web.UI.WebControls.Literal litAvailableBadge;

        protected global::System.Web.UI.WebControls.Repeater rptAvailable;

        protected global::System.Web.UI.WebControls.Panel pnlNoAvailable;
    }
}
