//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.NGO
{


    public partial class ngo_active_requests
    {

        protected global::System.Web.UI.WebControls.Label lblActionMessage;

        protected global::System.Web.UI.WebControls.Literal litAwaitingCount;

        protected global::System.Web.UI.WebControls.Literal litTransitCount;

        protected global::System.Web.UI.WebControls.Literal litArrivedCount;

        protected global::System.Web.UI.WebControls.Literal litMealsExpected;

        protected global::System.Web.UI.WebControls.Repeater rptRequests;

        protected global::System.Web.UI.WebControls.Panel pnlNoRequests;

        protected global::System.Web.UI.WebControls.Repeater rptCompleted;

        protected global::System.Web.UI.WebControls.Panel pnlNoCompleted;
    }
}
