//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.NGO
{


    public partial class NGOMaster
    {

        protected global::System.Web.UI.WebControls.ContentPlaceHolder NGOHeadContent;

        protected global::LeftoverFood.Controls.RoleSidebar roleSidebar;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder NGOPageHeading;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder NGOMainContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder NGOFooterScripts;
    }
}
