//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.Admin
{


    public partial class admin_dashboard
    {

        /// <summary>
        /// litAsAt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAsAt;

        /// <summary>
        /// btnRefresh control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnRefresh;

        /// <summary>
        /// lblActionMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblActionMessage;

        /// <summary>
        /// litTotalDonations control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litTotalDonations;

        /// <summary>
        /// litTotalNGOs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litTotalNGOs;

        /// <summary>
        /// litTotalUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litTotalUsers;

        /// <summary>
        /// litPendingApprovals control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litPendingApprovals;

        /// <summary>
        /// litPendingBadge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litPendingBadge;

        /// <summary>
        /// rptPending control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptPending;

        /// <summary>
        /// pnlNoPending control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlNoPending;

        /// <summary>
        /// rptRecentDonations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRecentDonations;

        /// <summary>
        /// pnlNoDonations control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoDonations;

        /// <summary>
        /// litFulfilment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFulfilment;

        /// <summary>
        /// barFulfilment control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl barFulfilment;

        /// <summary>
        /// litFulfilmentNote control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFulfilmentNote;

        /// <summary>
        /// litNgoResponse control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNgoResponse;

        /// <summary>
        /// barNgoResponse control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl barNgoResponse;

        /// <summary>
        /// litNgoResponseNote control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNgoResponseNote;

        /// <summary>
        /// litVolunteerFree control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litVolunteerFree;

        /// <summary>
        /// barVolunteerFree control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl barVolunteerFree;

        /// <summary>
        /// litVolunteerFreeNote control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litVolunteerFreeNote;

        /// <summary>
        /// litUserGrowth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUserGrowth;

        /// <summary>
        /// barUserGrowth control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl barUserGrowth;

        /// <summary>
        /// litUserGrowthNote control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUserGrowthNote;

        /// <summary>
        /// rptUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptUsers;
    }
}
