//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.Admin
{


    public partial class AdminMaster
    {

        protected global::System.Web.UI.WebControls.ContentPlaceHolder AdminHeadContent;

        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder AdminPageHeading;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder AdminMainContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder AdminFooterScripts;
    }
}
