//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.Admin
{


    public partial class food_approvals
    {

        protected global::System.Web.UI.WebControls.Label lblActionMessage;

        protected global::System.Web.UI.WebControls.Literal litExpiringSoon;

        protected global::System.Web.UI.WebControls.Literal litAwaitingReview;

        protected global::System.Web.UI.WebControls.Literal litApprovedMonth;

        protected global::System.Web.UI.WebControls.Literal litRejectedMonth;

        protected global::System.Web.UI.WebControls.Repeater rptPending;

        protected global::System.Web.UI.WebControls.Panel pnlNoPending;

        protected global::System.Web.UI.WebControls.Repeater rptProcessed;
    }
}
