//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.Admin
{
    public partial class users
    {
        /// <summary>
        /// litHeading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeading;

        /// <summary>
        /// litSubheading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSubheading;

        /// <summary>
        /// lblActionMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblActionMessage;

        /// <summary>
        /// litTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotal;

        /// <summary>
        /// litApproved control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litApproved;

        /// <summary>
        /// litPending control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPending;

        /// <summary>
        /// litSuspended control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSuspended;

        /// <summary>
        /// litTableHeading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTableHeading;

        /// <summary>
        /// litMetricA control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMetricA;

        /// <summary>
        /// litMetricB control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMetricB;

        /// <summary>
        /// rptUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptUsers;

        /// <summary>
        /// pnlEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        /// <summary>
        /// litEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmpty;
    }
}
