//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.Admin
{


    public partial class volunteer_assign
    {

        protected global::System.Web.UI.WebControls.Label lblActionMessage;

        protected global::System.Web.UI.WebControls.Literal litVerifiedVolunteers;

        protected global::System.Web.UI.WebControls.Literal litOnDelivery;

        protected global::System.Web.UI.WebControls.Literal litNeedAssignment;

        protected global::System.Web.UI.WebControls.Repeater rptNeedsAssignment;

        protected global::System.Web.UI.WebControls.Panel pnlNoNeedsAssignment;

        protected global::System.Web.UI.WebControls.Repeater rptActiveDeliveries;

        protected global::System.Web.UI.WebControls.Panel pnlNoActiveDeliveries;
    }
}
