//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.Donor
{


    public partial class donate_form
    {

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.TextBox txtFoodDescription;

        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        protected global::System.Web.UI.WebControls.DropDownList ddlDonorType;

        protected global::System.Web.UI.WebControls.TextBox txtQuantity;

        protected global::System.Web.UI.WebControls.DropDownList ddlUnit;

        protected global::System.Web.UI.WebControls.TextBox txtServings;

        protected global::System.Web.UI.WebControls.TextBox txtPreparedOn;

        protected global::System.Web.UI.WebControls.TextBox txtExpiryTime;

        protected global::System.Web.UI.WebControls.FileUpload fuPhoto;

        protected global::System.Web.UI.WebControls.CheckBox chkHalal;

        protected global::System.Web.UI.WebControls.CheckBox chkVegetarian;

        protected global::System.Web.UI.WebControls.CheckBox chkVegan;

        protected global::System.Web.UI.WebControls.CheckBox chkGlutenFree;

        protected global::System.Web.UI.WebControls.CheckBox chkNuts;

        protected global::System.Web.UI.WebControls.TextBox txtNotes;

        protected global::System.Web.UI.WebControls.TextBox txtPickupAddress;

        protected global::System.Web.UI.WebControls.DropDownList ddlCity;

        protected global::System.Web.UI.WebControls.TextBox txtAvailableFrom;

        protected global::System.Web.UI.WebControls.TextBox txtAvailableUntil;

        protected global::System.Web.UI.WebControls.TextBox txtContactPerson;

        protected global::System.Web.UI.WebControls.TextBox txtContactPhone;

        protected global::System.Web.UI.WebControls.DropDownList ddlPackaging;

        protected global::System.Web.UI.WebControls.DropDownList ddlPreferredNGO;

        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
