//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.Donor
{


    public partial class donor_dashboard
    {

        protected global::System.Web.UI.WebControls.Label lblActionMessage;

        protected global::System.Web.UI.WebControls.Literal litTotalDonations;

        protected global::System.Web.UI.WebControls.Literal litDelivered;

        protected global::System.Web.UI.WebControls.Literal litPending;

        protected global::System.Web.UI.WebControls.Literal litMealsProvided;

        protected global::System.Web.UI.WebControls.Repeater rptDonations;

        protected global::System.Web.UI.WebControls.Panel pnlNoDonations;

        protected global::System.Web.UI.WebControls.Literal litSuccessRate;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl barSuccessRate;

        protected global::System.Web.UI.WebControls.Literal litSuccessNote;

        protected global::System.Web.UI.WebControls.Literal litImpactMeals;

        protected global::System.Web.UI.WebControls.Literal litImpactInProgress;

        protected global::System.Web.UI.WebControls.Literal litTrust;

        protected global::System.Web.UI.WebControls.Repeater rptActivity;

        protected global::System.Web.UI.WebControls.Panel pnlNoActivity;
    }
}
