//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.Donor
{


    public partial class DonorMaster
    {

        protected global::System.Web.UI.WebControls.ContentPlaceHolder DonorHeadContent;

        protected global::LeftoverFood.Controls.RoleSidebar roleSidebar;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder DonorPageHeading;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder DonorMainContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder DonorFooterScripts;
    }
}
