//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.Donor
{


    public partial class track_donation
    {

        protected global::System.Web.UI.WebControls.Panel pnlNotFound;

        protected global::System.Web.UI.WebControls.Panel pnlContent;

        protected global::System.Web.UI.WebControls.Literal litDonationId;

        protected global::System.Web.UI.WebControls.Literal litPostedDate;

        protected global::System.Web.UI.WebControls.Repeater rptSteps;

        protected global::System.Web.UI.WebControls.Panel pnlVolunteerInfo;

        protected global::System.Web.UI.WebControls.Literal litDetailId;

        protected global::System.Web.UI.WebControls.Literal litFoodType;

        protected global::System.Web.UI.WebControls.Literal litCategory;

        protected global::System.Web.UI.WebControls.Literal litQuantity;

        protected global::System.Web.UI.WebControls.Literal litServings;

        protected global::System.Web.UI.WebControls.Literal litDietary;

        protected global::System.Web.UI.WebControls.Literal litPickupLocation;

        protected global::System.Web.UI.WebControls.Literal litNgoAssigned;

        protected global::System.Web.UI.WebControls.Literal litVolunteerAssigned;

        protected global::System.Web.UI.WebControls.Panel pnlExpiry;

        protected global::System.Web.UI.WebControls.Literal litTimeRemaining;

        protected global::System.Web.UI.WebControls.Literal litExpiryTime;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl expiryFill;

        protected global::System.Web.UI.WebControls.Literal litPostedTime;

        protected global::System.Web.UI.WebControls.Literal litExpiryTime2;
    }
}
