//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.Volunteer
{


    public partial class VolunteerMaster
    {

        protected global::System.Web.UI.WebControls.ContentPlaceHolder VolunteerHeadContent;

        protected global::LeftoverFood.Controls.RoleSidebar roleSidebar;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder VolunteerPageHeading;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder VolunteerMainContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder VolunteerFooterScripts;
    }
}
