//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftoverFood.Volunteer
{


    public partial class volunteer_dashboard
    {

        protected global::System.Web.UI.WebControls.Literal litActiveTasksInline;

        protected global::System.Web.UI.WebControls.Label lblActionMessage;

        protected global::System.Web.UI.WebControls.Literal litActiveTasks;

        protected global::System.Web.UI.WebControls.Literal litDeliveriesDone;

        protected global::System.Web.UI.WebControls.Repeater rptActiveTasks;

        protected global::System.Web.UI.WebControls.Panel pnlNoActiveTasks;

        protected global::System.Web.UI.WebControls.Repeater rptCompleted;

        protected global::System.Web.UI.WebControls.Panel pnlNoCompleted;
    
        protected global::System.Web.UI.WebControls.CheckBox chkShareLocation;
}
}
